const amcList = {
  data: [
    {
      amcId: 1,
      amcCode: "BirlaSunLifeMutualFund_MF",
      amcName: "Aditya Birla Sun Life Mutual Fund",
      RTA: "CAMS",
      RTA_code: "B",
      isActive: 1,
      dateAdded: "2021-02-04",
      amcImage: "undefinedimages/amc/1_BirlaSunLifeMutualFund_MF.png",
    },
    {
      amcId: 2,
      amcCode: "AXISMUTUALFUND_MF",
      amcName: "Axis Mutual Fund",
      RTA: "Karvy",
      RTA_code: null,
      isActive: 1,
      dateAdded: "2021-02-04",
      amcImage: "undefinedimages/amc/2_AXISMUTUALFUND_MF.png",
    },
    {
      amcId: 16,
      amcCode: "CANARAROBECOMUTUALFUND_MF",
      amcName: "Canara Robeco Mutual Fund",
      RTA: "Karvy",
      RTA_code: null,
      isActive: 1,
      dateAdded: "2021-02-04",
      amcImage: "undefinedimages/amc/16_CANARAROBECOMUTUALFUND_MF.png",
    },
    {
      amcId: 6,
      amcCode: "DSP_MF",
      amcName: "DSP Mutual Fund",
      RTA: "CAMS",
      RTA_code: "D",
      isActive: 1,
      dateAdded: "2021-02-04",
      amcImage: "undefinedimages/amc/6_DSP_MF.png",
    },
    {
      amcId: 21,
      amcCode: "EDELWEISSMUTUALFUND_MF",
      amcName: "Edelweiss Mutual Fund",
      RTA: "Karvy",
      RTA_code: null,
      isActive: 1,
      dateAdded: "2021-02-04",
      amcImage: "undefinedimages/amc/21_EDELWEISSMUTUALFUND_MF.png",
    },
    {
      amcId: 7,
      amcCode: "FRANKLINTEMPLETON",
      amcName: "Franklin Templeton Mutual Fund",
      RTA: "CAMS",
      RTA_code: "FT",
      isActive: 1,
      dateAdded: "2021-02-04",
      amcImage: "undefinedimages/amc/7_FRANKLINTEMPLETON.png",
    },
    {
      amcId: 8,
      amcCode: "HDFCMutualFund_MF",
      amcName: "HDFC Mutual Fund",
      RTA: "CAMS",
      RTA_code: "H",
      isActive: 1,
      dateAdded: "2021-02-04",
      amcImage: "undefinedimages/amc/8_HDFCMutualFund_MF.png",
    },
    {
      amcId: 23,
      amcCode: "HSBCMUTUALFUND_MF",
      amcName: "HSBC Mutual Fund",
      RTA: "CAMS",
      RTA_code: "O",
      isActive: 1,
      dateAdded: "2021-02-04",
      amcImage: "undefinedimages/amc/23_HSBCMUTUALFUND_MF.png",
    },
    {
      amcId: 9,
      amcCode: "ICICIPrudentialMutualFund_MF",
      amcName: "ICICI Prudential Mutual Fund",
      RTA: "CAMS",
      RTA_code: "P",
      isActive: 1,
      dateAdded: "2021-02-04",
      amcImage: "undefinedimages/amc/9_ICICIPrudentialMutualFund_MF.png",
    },
    {
      amcId: 20,
      amcCode: "INVESCOMUTUALFUND_MF",
      amcName: "Invesco Mutual Fund",
      RTA: "Karvy",
      RTA_code: null,
      isActive: 1,
      dateAdded: "2021-02-04",
      amcImage: "undefinedimages/amc/20_INVESCOMUTUALFUND_MF.png",
    },
    {
      amcId: 10,
      amcCode: "KOTAKMAHINDRAMF",
      amcName: "Kotak Mutual Fund",
      RTA: "CAMS",
      RTA_code: "K",
      isActive: 1,
      dateAdded: "2021-02-04",
      amcImage: "undefinedimages/amc/10_KOTAKMAHINDRAMF.png",
    },
    {
      amcId: 14,
      amcCode: "MIRAEASSET",
      amcName: "Mirae Asset Mutual Fund",
      RTA: "Karvy",
      RTA_code: null,
      isActive: 1,
      dateAdded: "2021-02-04",
      amcImage: "undefinedimages/amc/14_MIRAEASSET.png",
    },
    {
      amcId: 13,
      amcCode: "MOTILALOSWAL_MF",
      amcName: "Motilal Oswal Mutual Funds",
      RTA: "Karvy",
      RTA_code: null,
      isActive: 1,
      dateAdded: "2021-02-04",
      amcImage: "undefinedimages/amc/13_MOTILALOSWAL_MF.png",
    },
    {
      amcId: 17,
      amcCode: "NipponIndiaMutualFund_MF",
      amcName: "Nippon India Mutual Fund",
      RTA: "Karvy",
      RTA_code: null,
      isActive: 1,
      dateAdded: "2021-02-04",
      amcImage: "undefinedimages/amc/17_NipponIndiaMutualFund_MF.png",
    },
    {
      amcId: 31,
      amcCode: "PGIMINDIAMUTUALFUND_MF",
      amcName: "PGIM India Mutual Fund",
      RTA: "Karvy",
      RTA_code: null,
      isActive: 1,
      dateAdded: "2021-02-04",
      amcImage: "undefinedimages/amc/31_PGIMINDIAMUTUALFUND_MF.png",
    },
    {
      amcId: 19,
      amcCode: "PPFAS_MF",
      amcName: "PPFAS Mutual Fund",
      RTA: "CAMS",
      RTA_code: "PP",
      isActive: 1,
      dateAdded: "2021-02-04",
      amcImage: "undefinedimages/amc/19_PPFAS_MF.png",
    },
    {
      amcId: 33,
      amcCode: "QUANTUMMUTUALFUND_MF",
      amcName: "Quantum Mutual Fund",
      RTA: "Karvy",
      RTA_code: null,
      isActive: 1,
      dateAdded: "2021-02-04",
      amcImage: "undefinedimages/amc/33_QUANTUMMUTUALFUND_MF.png",
    },
    {
      amcId: 12,
      amcCode: "SBIMutualFund_MF",
      amcName: "SBI Mutual Fund",
      RTA: "CAMS",
      RTA_code: "L",
      isActive: 1,
      dateAdded: "2021-02-04",
      amcImage: "undefinedimages/amc/12_SBIMutualFund_MF.png",
    },
    {
      amcId: 37,
      amcCode: "TATAMutualFund_MF",
      amcName: "Tata Mutual Fund",
      RTA: "CAMS",
      RTA_code: "T",
      isActive: 1,
      dateAdded: "2021-02-04",
      amcImage: "undefinedimages/amc/37_TATAMutualFund_MF.png",
    },
    {
      amcId: 41,
      amcCode: "UTIMUTUALFUND_MF",
      amcName: "UTI Mutual Fund",
      RTA: "Karvy",
      RTA_code: null,
      isActive: 1,
      dateAdded: "2021-02-04",
      amcImage: "undefinedimages/amc/41_UTIMUTUALFUND_MF.png",
    },
  ],
};

const menuItems = [
  // {
  //   id: 1,
  //   title: "Top Funds",
  //   items: [
  //     {
  //       path: "#!",
  //       label: "Best Largecap Funds",
  //     },
  //     {
  //       path: "#!",
  //       label: "Best Midcap Funds",
  //     },
  //     {
  //       path: "#!",
  //       label: "Best Smallcap Funds",
  //     },
  //     {
  //       path: "#!",
  //       label: "Best Flexicap Funds",
  //     },
  //     {
  //       path: "#!",
  //       label: "Best Liquid Funds",
  //     },
  //     {
  //       path: "#!",
  //       label: "Best SIP funds",
  //     },
  //   ],
  // },

  {
    id: 0,
    title: "Calculators",
    items: [
      {
        path: "/sip-calculator",
        label: "SIP Calculator",
      },
      {
        path: "/ppf-calculator",
        label: "PPF Calculator",
      },
      {
        path: "/crorepati-calculator",
        label: "Crorepati Calculator",
      },
      {
        path: "/lumpsum-calculator",
        label: "Lumpsum Calculator",
      },
      {
        path: "/sip-delay-calculator",
        label: "SIP Delay Calculator",
      },
      {
        path: "/mssc-calculator",
        label: "MSSC Calculator",
      },
      {
        path: "/emergency-fund-calculator",
        label: "Emergency Fund Calculator",
      },
      {
        path: "/ssy-calculator",
        label: "SSY Calculator",
      },
    ],
  },
  {
    id: 1,
    title: "Legal",
    items: [
      {
        path: "/terms-of-use",
        label: "Terms of Use",
      },
      {
        path: "/terms-and-conditions",
        label: "Terms and Conditions",
      },
      {
        path: "/privacy-policy",
        label: "Privacy Policy ",
      },
      // {
      //   path: "#!",
      //   label: "Disclaimer",
      // },
      // {
      //   path: "#!",
      //   label: "Images & B-roll",
      // },
      // {
      //   path: "#!",
      //   label: "Permissions",
      // },
    ],
  },
  {
    id: 2,
    title: "About Us",
    items: [
      {
        path: "/about-us",
        label: "About Us",
      },
      // {
      //   path: "#!",
      //   label: "Customer Support",
      // },
      // {
      //   path: "#!",
      //   label: "Commission Disclosure",
      // },
      // {
      //   path: "#!",
      //   label: "Copyright",
      // },
      // {
      //   path: "#!",
      //   label: "Popular Campaign",
      // },
    ],
  },
  {
    id: 3,
    title: "Learn",
    items: [
      {
        path: "/blog",
        label: "Blog",
      },
      // {
      //   path: "#!",
      //   label: "Customer Support",
      // },
      // {
      //   path: "#!",
      //   label: "Commission Disclosure",
      // },
      // {
      //   path: "#!",
      //   label: "Copyright",
      // },
      // {
      //   path: "#!",
      //   label: "Popular Campaign",
      // },
    ],
  },
  // {
  //   id: 5,
  //   title: "Policy",
  //   items: [
  //     {
  //       path: "#!",
  //       label: "Application security",
  //     },
  //     {
  //       path: "#!",
  //       label: "Software principles",
  //     },
  //     {
  //       path: "#!",
  //       label: "Unwanted software policy",
  //     },
  //     {
  //       path: "#!",
  //       label: "Responsible supply chain",
  //     },
  //   ],
  // },
];
export { amcList, menuItems };
